- id: "api:authorizer"
  upstream:
    preserve_host: true
    url: "http://authorizer:5004"
  match:
    url: "http://localhost:8080/api/v1/authorizer/<**>"
    methods:
      - GET
      - POST
      - DELETE
  authenticators:
    - handler: noop
  mutators:
    - handler: noop
  authorizer:
    handler: allow

- id: "api:account"
  upstream:
    preserve_host: true
    url: "http://account:5003"
  match:
    url: "http://localhost:8080/api/v1/account/<**>"
    methods:
      - GET
      - POST
  authenticators:
    - handler: bearer_token
  mutators:
    - handler: header
  authorizer:
    handler: allow
